# Generated by Django 4.1.7 on 2023-03-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_book', models.CharField(max_length=200, verbose_name='Название книги')),
                ('book_series', models.CharField(max_length=50, verbose_name='Серия книг')),
                ('book_genre', models.CharField(max_length=20, verbose_name='Жанр')),
                ('year_publishing', models.IntegerField(verbose_name='Год издания')),
                ('number_pages', models.IntegerField(verbose_name='Количество страниц')),
                ('size', models.CharField(max_length=100, verbose_name='Формат')),
                ('ISBN', models.CharField(max_length=100, verbose_name='ISBN')),
                ('publishing_house', models.CharField(max_length=40, verbose_name='Издательство')),
                ('in_stock', models.IntegerField(verbose_name='Количество в наличии')),
                ('available_to_order', models.BooleanField(default=True, verbose_name='Доступна к заказу')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг (0-10)')),
                ('date_inclusion', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения карточки')),
            ],
        ),
    ]
