# Generated by Django 4.1.7 on 2023-03-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя автора')),
                ('author_discription', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='available_to_order',
        ),
        migrations.RemoveField(
            model_name='book',
            name='in_stock',
        ),
    ]
