# Generated by Django 4.1.7 on 2023-03-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_remove_book_available_to_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.ManyToManyField(default='Автор', related_name='authors', to='books.author'),
        ),
    ]
